language: scala
scala: 2.12.10
jdk: oraclejdk8
sudo: false
dist: trusty

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)


env:
  global:
    - TRAVIS_NODE_VERSION="10"
    - TRAVIS_YARN_VERSION="1.10.1"

jobs:
  include:
    - env: TEST="sbt ci-test"
      script: sbt ci-test
    - jdk: openjdk11
      env: TEST="sbt ci-test"
      script: sbt ci-test
    - env: TEST="sbt ci-test"
      scala: 2.11.12
      script: sbt ci-test
    - env: TEST="sbt scripted"
      script: sbt scripted
    - env: TEST=scalafmt
      script: ./bin/scalafmt --test
    - stage: release
      script: sbt ci-release

cache:
  yarn: true
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_install:
  # Install Node.js and yarn.
  - nvm install "$TRAVIS_NODE_VERSION"
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "$TRAVIS_YARN_VERSION"
  - export PATH=$HOME/.yarn/bin:$PATH

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local
